import test from 'node:test';import assert from 'node:assert/strict';import {validateUpload,transition,editTranscript,canApprove,retry,costAllowed,costStatus,estimateStorageCost,notificationFor,makeCopy} from '../src/domain.js';
test('validates media limits and aspect ratio',()=>{assert.equal(validateUpload({sizeBytes:1e9,durationSeconds:10,width:1080,height:1920}).length,0);assert.ok(validateUpload({sizeBytes:1e9+1,durationSeconds:9,width:1920,height:1080}).length>=3)});
test('state transitions and render invalidation',()=>{let p={state:'queued',renderStatus:'current',outputKey:'x'};p=transition(p,'processing');p=transition(p,'ready for review');assert.ok(canApprove(p));p=editTranscript(p,[{text:'edited'}]);assert.equal(p.renderStatus,'outdated');assert.ok(!canApprove(p))});
test('retries max twice after initial attempt',()=>{let p={attempts:0,state:'processing'};p=retry(p);p=retry(p);p=retry(p);assert.equal(p.state,'failed')});
test('cost ceiling',()=>{assert.ok(costAllowed(9,1));assert.ok(!costAllowed(9.01,1))});
test('cost status surfaces warnings before the hard ceiling',()=>{assert.equal(costStatus(1,1).warning,null);assert.equal(costStatus(3,1).warning,'warning');assert.equal(costStatus(7,1).warning,'critical');assert.equal(costStatus(9,1).allowed,true);assert.equal(costStatus(9.5,1).allowed,false)});
test('notifications flag failures, duplicates and ready-for-review renders',()=>{assert.equal(notificationFor({state:'failed',attempts:3,filename:'a.mp4'}).level,'error');assert.equal(notificationFor({state:'queued',duplicateOf:'x',filename:'a.mp4'}).level,'warning');assert.equal(notificationFor({state:'ready for review',renderStatus:'current',filename:'a.mp4'}).level,'info');assert.equal(notificationFor({state:'queued',renderStatus:'none',filename:'a.mp4'}),null)});
test('storage cost scales with uploaded bytes and feeds the warning tiers',()=>{const small=estimateStorageCost(1_000_000_000);assert.ok(small>0 && small<1);const big=estimateStorageCost(400_000_000_000);assert.equal(costStatus(0,big).warning,'critical');assert.equal(costStatus(0,small).warning,null)});
test('copy removes fillers, creates four hashtags and flags guarantees',()=>{let c=makeCopy([{text:'Um use math practice to score guaranteed results.'}]);assert.ok(!/\bum\b/i.test(c.description));assert.equal(c.hashtags.length,4);assert.equal(c.flagged,true)});
