export const STATES = Object.freeze({ QUEUED:'queued', PROCESSING:'processing', REVIEW:'ready for review', APPROVAL:'awaiting approval', COMPLETE:'manual-complete', FAILED:'failed' });
export function validateUpload({sizeBytes,durationSeconds,width,height,mime='video/mp4'}) { const errors=[]; if(sizeBytes>1_000_000_000) errors.push('Video must be at most 1 GB'); if(durationSeconds<10||durationSeconds>90) errors.push('Video must be 10–90 seconds'); if(width/height < .55 || width/height > .57) errors.push('Video must be vertical 9:16'); if(!mime.startsWith('video/')) errors.push('Upload must be a video'); return errors; }
export function transition(project,next){ const allowed={queued:['processing'],processing:['queued','ready for review','failed'],[STATES.REVIEW]:[STATES.APPROVAL,'processing'],[STATES.APPROVAL]:[STATES.COMPLETE,STATES.REVIEW],failed:['queued']}; if(!allowed[project.state]?.includes(next)) throw new Error(`Invalid transition ${project.state} -> ${next}`); return {...project,state:next}; }
export function editTranscript(project,segments){ return {...project,segments,renderStatus:'outdated',state:STATES.REVIEW}; }
export function canApprove(project){ return project.state===STATES.REVIEW && project.renderStatus==='current' && !!project.outputKey; }
export function retry(project){ const attempts=project.attempts+1; if(attempts>=3) return {...project,attempts,state:STATES.FAILED}; return {...project,attempts,state:STATES.QUEUED}; }
export const COST_CEILING=10, COST_WARN_LOW=4, COST_WARN_HIGH=8;
export function costAllowed(spend,estimated=0){ return spend+estimated<=COST_CEILING; }
export function costStatus(spend,estimated=0){ const projected=spend+estimated; const warning=projected>=COST_WARN_HIGH?'critical':projected>=COST_WARN_LOW?'warning':null; return {allowed:projected<=COST_CEILING,projected,warning,ceiling:COST_CEILING}; }
export function duplicateKey({sha256,sizeBytes}) { return `${sha256}:${sizeBytes}`; }
export const STORAGE_COST_PER_GB=0.023;
export function estimateStorageCost(sizeBytes){ return (sizeBytes/1_000_000_000)*STORAGE_COST_PER_GB; }
export function notificationFor(project){ if(project.state===STATES.FAILED) return {level:'error',message:`"${project.filename}" failed after ${project.attempts} attempts.`}; if(project.duplicateOf) return {level:'warning',message:`"${project.filename}" duplicates an existing upload.`}; if(project.state===STATES.REVIEW && project.renderStatus==='current') return {level:'info',message:`"${project.filename}" is ready for review.`}; return null; }
const bannedGuarantees=/guarantee|guaranteed|admission|you will score|urgent|last chance/i;
export function makeCopy(segments,context=''){ const text=segments.map(s=>s.text.trim()).join(' ').replace(/\b(um|uh)\b[,.]?\s*/gi,'').replace(/\s+/g,' ').trim(); const words=text.split(/\s+/).filter(Boolean); const hook=(words.slice(0,10).join(' ')||'Study smarter, score stronger.').replace(/[.!?]*$/,'!'); const description=(text+' '+context).trim().slice(0,220).trim(); const topic=(text.match(/\b(reading|math|grammar|SAT|study|practice|vocabulary)\b/gi)||['study']).map(x=>x.toLowerCase()); const tags=[...new Set(topic)].slice(0,4); while(tags.length<4) tags.push(['sat','students','learning','testprep'][tags.length]); return {hook,description,hashtags:tags.map(x=>'#'+x.replace(/[^a-z0-9]/gi,'')),flagged:bannedGuarantees.test(text+' '+context)}; }
